[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
lib_deps = 
    olikraus/U8g2@^2.35.19
    z3t0/IRremote@^3.5.2
    arduino-libraries/SD@^1.2.4
    adafruit/Adafruit NeoPixel@^1.12.0